### ISSUE TITLE
Update Requirements to add Flask-RESTX

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#107]
**As a** Developer
**I need** the ability to have the Flask-RESTX package included in the application
**So that** I can refactor the application using this framework.
   
 ### Details and Assumptions
 * Add/update the following packages as listed in the requirements.txt file.
 
Werkzeug==2.0.3
Flask-RESTX==0.5.1
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When the Flask-RESTX package is added to the app
 Then it can be used to refactor the code.
```

**Comment by Matt-Kou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/107?planning-poker) with Zenhub @bf2285 @haoruigao @MahamArif
