### ISSUE TITLE
Delete An Order API has no not found response

### ISSUE THREAD

**Issue by SteambreadC** [CSCI-GA-2820-SP23-003/orders#114]
Describe the bug
Delete An Order API doesn't respond with 404_NOT_FOUND when the order is not in the database.

To Reproduce

Open the project in a container
Start service
Try deleting an unexisting order id
The result shown is 'Order has been Deleted!'

Observed behavior
The result shown is 'Order has been Deleted!'

**Comment by MahamArif** [comment]
This behavior is not required for DELETE order. Delete API will always return 204 NO CONTENT.
