### ISSUE TITLE
Test Swagger Documentation

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#128]
**As a** Orders Manager/System Administrator
**I need** the ability to test swagger documentation
**So that** I know all the functions are well documented
   
 ### Details and Assumptions
 * Conduct manual testing to Swagger documentation and see if every functions required are well documented
 * Please also include screenshot about which functions you already tested
 * This should be done after the new cluster was created
 * DEV BASE_URL: `http://159.122.186.49:31001`
 * PROD BASE_URL: `http://159.122.186.49:31002`
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the Order service is running and Swagger annotations are added
When I access the UI
Then I can see the swagger documentation.
```

**Comment by Matt-Kou** [comment]
# Local tests
## Get orders 
### Get with an empty body
![image](https://user-images.githubusercontent.com/36983956/235201050-eb6083b5-696d-413c-90b7-307c9fe809ca.png)
### Get customer_id
#### existing
![image](https://user-images.githubusercontent.com/36983956/235201319-07fe78e8-662a-4219-aa37-03994cbf11fe.png)
#### non-existing
![image](https://user-images.githubusercontent.com/36983956/235201667-b3ce802d-cb66-4294-92b5-f5aba1af4adc.png)
### Get status
#### existing
![image](https://user-images.githubusercontent.com/36983956/235201967-e0aad01b-8c18-4ded-b9e9-ff050b9655a8.png)
#### non-existing
![image](https://user-images.githubusercontent.com/36983956/235202096-9e6db6ba-7d7c-4c5a-a44f-efb7fecea886.png)
### Get product_id
#### existing
![image](https://user-images.githubusercontent.com/36983956/235202347-2793424e-1b25-46b6-94c8-fad597659104.png)
#### non-existing
![image](https://user-images.githubusercontent.com/36983956/235202430-b76b552c-1983-4a61-adb2-978d000798c5.png)
## Create an order (post)
### valid payload
![image](https://user-images.githubusercontent.com/36983956/235203585-b28951a1-c848-46a9-ba24-ee7cdecea639.png)
### invalid payload
![image](https://user-images.githubusercontent.com/36983956/235203930-cb81ecb2-bc46-480e-94bc-f631af486271.png)
![image](https://user-images.githubusercontent.com/36983956/235204165-e15b5619-34b1-4a8a-8418-1ca069847a0b.png)
## Delete an Order
### valid order_id
![image](https://user-images.githubusercontent.com/36983956/235205253-3e964ef3-c885-46fb-a17f-7637fee94496.png)
order is confirmed to be deleted:
![image](https://user-images.githubusercontent.com/36983956/235205402-683403d2-a3a5-48c3-964f-2a5281126f72.png)
### invalid order_id
![image](https://user-images.githubusercontent.com/36983956/235206056-49057bd6-28cd-4162-bc46-2af7d512740e.png)
Confirmation that nothing changed:
![image](https://user-images.githubusercontent.com/36983956/235206132-b8a80dbe-f018-41b7-868c-6db0ab28658e.png)
## Update an order (put)
### valid payload
![image](https://user-images.githubusercontent.com/36983956/235209626-609d8f80-a913-467f-abf9-86230cae76ab.png)
### invalid payload
![image](https://user-images.githubusercontent.com/36983956/235209471-48dbefef-1b38-43ca-b66d-9935abf065f2.png)
### invalid order_id
![image](https://user-images.githubusercontent.com/36983956/235209751-5e02239e-c8a9-4a3c-9d92-ce5565672dce.png)
## Get an order
### valid order_id
![image](https://user-images.githubusercontent.com/36983956/235209929-61595210-ca98-4da6-a280-01be1b1f0af4.png)
### invalid order_id
![image](https://user-images.githubusercontent.com/36983956/235209991-5050b848-7a55-4aba-bdd8-0cab3638195b.png)
## Cancel an order (put)
### valid order_id
#### Cancel a confirmed order
![image](https://user-images.githubusercontent.com/36983956/235214036-af145a81-e3ef-47fe-b49b-85fa4e9c2f56.png)
#### cancel canceled order
![image](https://user-images.githubusercontent.com/36983956/235214141-fb7f3cc8-b291-4309-b15a-b9e041cf4048.png)
### invalid order_id
![image](https://user-images.githubusercontent.com/36983956/235214225-b5deee2e-cd17-4ad5-83a5-fd7e87cf2bf7.png)
## List items (get)
### existing order
![image](https://user-images.githubusercontent.com/36983956/235215384-73c535d2-08c7-4f90-a9ac-9831ad315632.png)
### non-existing order
![image](https://user-images.githubusercontent.com/36983956/235217182-2def5d9b-ca48-4d42-8ce9-126c19f20eca.png)
## Create an item in an order
## existing order_id
![image](https://user-images.githubusercontent.com/36983956/235218825-b5c3160c-cd7f-4c0c-9d1c-a107cecd8472.png)
### non-existing order_id
![image](https://user-images.githubusercontent.com/36983956/235218921-fa3f040e-f01b-480e-8cd8-cf269f47dbff.png)
### invalid payload
![image](https://user-images.githubusercontent.com/36983956/235219118-eae67c78-83b6-4ead-827f-85cc10e5f19a.png)
## Delete an item
Before delete:
![image](https://user-images.githubusercontent.com/36983956/235219678-3fe900d6-a13e-4a5b-9179-fcadb9eff05b.png)
### Delete non-existing item
![image](https://user-images.githubusercontent.com/36983956/235219481-13a229e4-81d3-43de-a441-63623b11e251.png)
After delete:
![image](https://user-images.githubusercontent.com/36983956/235220537-ce4f1945-4230-4e05-af14-52666cdd8524.png)
### Delete existing item
![image](https://user-images.githubusercontent.com/36983956/235220604-a0b8e77e-325f-4d8c-b2c4-85a5dc0c4a33.png)
After delete:
![image](https://user-images.githubusercontent.com/36983956/235220649-5739721c-c4e8-4f5b-9392-9de7b23cfce1.png)
## Update an item from an order
### existing item
![image](https://user-images.githubusercontent.com/36983956/235224358-5a0b07d5-e332-4334-be9a-b7aff65684c2.png)
### non-existing item
![image](https://user-images.githubusercontent.com/36983956/235224455-84e63cc5-45d9-447f-b44d-3e3a59f73fd0.png)
### invalid payload
![Uploading image.png…]()
