### ISSUE TITLE
Test Orders APIs on Dev Namespace (Kubernetes Cluster)

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#137]
**As a** Orders Developer
**I need** to test Orders APIs on Dev Namespace (Kubernetes Cluster)
**So that** I can ensure that the API changes and updates are functional before being deployed to production
   
 ### Details and Assumptions
 * The Orders APIs are deployed on the Dev Namespace of a Kubernetes Cluster.
* The Kubernetes Cluster is already set up and running.
* The Orders API endpoints can be accessed through a web browser or API testing tool.
* Testing will be conducted manually to ensure the API is functioning correctly.
* The testing will include verifying the functionality of each Orders API endpoint.
* Any bugs or issues discovered during testing will be reported and documented.
* The Orders API should never throw error code 500.
* DEV BASE_URL: `http://159.122.186.49:31001`
* PROD BASE_URL: `http://159.122.186.49:31002`
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the Orders APIs are deployed on the Dev Namespace of a Kubernetes Cluster
When I access the Orders API endpoints through a web browser or API testing tool
Then I can verify that each Orders API endpoint is functioning correctly.

Given I have tested all Orders API endpoints on the Dev Namespace of the Kubernetes Cluster
When I report any bugs or issues discovered during testing
Then the issues can be addressed before the Orders API is deployed to production.
```

**Comment by haoruigao** [comment]
### Create Order
Create Order - Happy Path
![create_order.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/d9b4ee1d-6c2c-4943-8498-ee84f4476471)
Create Order - Bad Path
![create_order_bad.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/ed330fb0-677b-4aad-8a0b-afd8e467c273)

### Retrieve Order
Retrieve Order - Happy Path
![retreive_order.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/11ad4aa3-8c86-412a-916d-c38cf25945a9)
Retrieve Order - Bad Path
![retreive_order_not found.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/3137ffdc-68b2-4c16-8a76-48cf302e3990)

### Update Order
Update Order - Happy Path
![update_order.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/b245c23b-b5ee-4129-af33-3acb792999f2)
Update Order - Bad Path
![update_not found.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/f4406f27-f6e9-4fd1-a6e5-0493615e5a38)

### Delete Order
![delete_order_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/872bb180-2c83-42dc-87a4-a5fe0067abfa)

### Search Order
Search Order - Happy Path
![search_order.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/6a30e8f1-03a5-452d-854b-4855fa81dc9e)
Search Order - Bad Path
![search_order_id_notfound.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/48e0cbb2-1794-422d-9cf0-6ee6f9189ed4) 

### Cancel Order
Cancel Order - Happy Path
![cancel_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/ca52d6d7-b3c1-43f1-b71b-708ec4c0d1f4)
Cancel Order - Bad Path
![cancel_nosuch id.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/68cc5073-c77a-4999-97c6-a57d56e349fe)![cancel_notwork.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/08034080-fbe9-4b7f-8197-483c535f9aad)![cancel_no_id.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/0a062bac-431a-4d2d-99ce-6bbac405bc91)

**Comment by haoruigao** [comment]
### Create Item
Create Item - Happy Path
![create_item_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/20233aab-268d-4e53-8e87-d7d4207e68b6)
![Screenshot 2023-05-01 at 11.58.02.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/75c41a2b-867f-46aa-9537-18d917951280)
Create Item - Bad Path
![create_item_no_order_id.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/e9458c11-9d3d-4974-943a-fd38cfbccc9a)
![Screenshot 2023-05-01 at 11.56.27.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/878473ac-5081-4ac0-9a12-140c7d50df9d)
![create_item_no_product_id.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/5f2b8447-8dff-48ab-9c9b-5d7dec15da98)![Screenshot 2023-05-01 at 11.59.19.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/37a392d1-53b8-4d1a-9e48-d686244dff70)![create_item_no_price.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/011e4f2f-b997-4af0-866e-3a6e63e3588b)![Screenshot 2023-05-01 at 12.04.20.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/a644274c-60b3-4c76-b353-078eabab9ebf)

**Comment by haoruigao** [comment]
### Retrieve Item
Retrieve item - Happy Path
![retreive_item.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/47c8fc7f-ddb5-4045-90f4-4a3f354c46f9)
![Screenshot 2023-05-01 at 12.05.51.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/ad66e9a6-4329-4d76-8702-eeb8232ad7d8)

Retrieve Item - Bad Path
![retrieve_bad.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/947803cb-0342-4799-af85-3ae07cfa3eba)![Screenshot 2023-05-01 at 12.06.37.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/2e74465c-0a19-410c-b96f-11bcc07e62f3)

**Comment by haoruigao** [comment]
### Update Item
Update Item - Happy Path
![update_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/e674a615-a561-40db-8d42-a00f877d989d)
![Screenshot 2023-05-01 at 23.28.02.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/de66d580-47bf-403f-bddb-1a8e854ed8ad)
Update Item - Bad Path
![update_no_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/29ef7047-f12b-414f-bf40-56fb08ab8953)
![Screenshot 2023-05-01 at 23.31.28.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/1354a71f-53d6-4a14-8a9f-d9ea644a9650)![update_no_item.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/a14bd3a1-eb2f-486f-90f9-b07be93db376)![Screenshot 2023-05-01 at 23.37.00.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/d73074c0-c239-4d86-98b8-133b2183b1cd)

**Comment by haoruigao** [comment]
### Delete Item
Delete item - Happy Path
![delete_item_success.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/70a6b96c-b0d3-4153-8bf0-ae2e93f2e7bd)
![Screenshot 2023-05-01 at 23.39.39.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/590f8691-91b0-495d-a7f4-484ce6431293)

**Comment by haoruigao** [comment]
### List Item
List item - Happy Path
![Screenshot 2023-05-02 at 14.30.20.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/d0661895-3e8d-49aa-bd96-9597bee72a26)
![Screenshot 2023-05-01 at 23.28.02.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/fd72c35f-c170-4c10-9675-9bfe01f7a88c)
List item - Bad Path
![Screenshot 2023-05-02 at 14.30.49.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/824f819c-58ed-47b8-8c46-944d549e6c67)
![Screenshot 2023-05-02 at 14.30.54.png](https://images.zenhubusercontent.com/63e5c02e7080145046c0c322/fbca3407-7a7a-471d-bf55-a917f0436cde)
