### ISSUE TITLE
Need the ability to Delete an Item from an order

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#14]
**As a** Order Manager
**I need** the ability to delete an item from an order
**So that** we can update the database accordingly when an item is removed from an order
   
 ### Details and Assumptions
Deleting an item will not remove order information.

Following are the cases for deleting item API.

1. If the order doesn't exist by id, return a 404_NOT_FOUND error.
2. If an order exists, try to find the item by both the order id and item id. If the item is found, delete it.
3. If the item is not found, do nothing.
4. Return HTTP_204_NO_CONTENT in cases 2 & 3.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I delete an item from an order
 Then that item for that order should not exist in the database
```

**Comment by MahamArif** [comment]
Should we remove the order if all the items got deleted?

**Comment by MahamArif** [comment]
Updated the story description as discussed with the professor:

1. If the order doesn't exist by id, return a 404_NOT_FOUND error.
2. If an order exists, try to find the item by both the order id and item id. If the item is found, delete it.
3. If the item is not found, do nothing.
4. Return HTTP_204_NO_CONTENT in cases 2 & 3.
