### ISSUE TITLE
UI should not update with negative values and Search with no query parameters is throwing 500

### ISSUE THREAD

**Issue by Matt-Kou** [CSCI-GA-2820-SP23-003/orders#144]
**Observed behavior**
1. Update with negative numerical values (currently no error, but it should be 400)
2. Update with omitting any of the required fields, clicking update multiple times
3. Search with no query parameters is sometimes throwing 500.

**Screenshots**
1. When click on list:
![image.png](https://images.zenhubusercontent.com/63e6fa71e9adb86bbc782c53/e5b7e31b-adee-4afa-8b65-0f3176ebb3ac)
2. Adding negative numerical values:
![image.png](https://images.zenhubusercontent.com/63e6fa71e9adb86bbc782c53/4293f2d5-2de3-4144-a688-244e22e3b785)

**Comment by MahamArif** [comment]
Search functionality seems to work fine. Apparently, the service on Kubernetes is throwing 500 sometimes when so many requests are issued from different browsers. This is certainly because of high CPU usage.
