### ISSUE TITLE
Need the ability to List all orders

### ISSUE THREAD

**Issue by Matt-Kou** [CSCI-GA-2820-SP23-003/orders#15]
**As a** Order Manager
**I need** the ability to List all orders
**So that** I would know what orders I have placed
   
 ### Details and Assumptions
 * The API will return the following order information:
List of all orders that I have created.

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given my client ID
 When I list all orders
 Then I can see all order IDs that I have placed
```

**Comment by MahamArif** [comment]
This issue is duplicated by #12.
