### ISSUE TITLE
Need the ability to Update an item in an order

### ISSUE THREAD

**Issue by SteambreadC** [CSCI-GA-2820-SP23-003/orders#20]
**As an** Order Manager
**I need** the ability to update an item for an order
**So that** I can modify items details in an order without modifying the whole order

 ### Details and Assumptions
 * This is the subordinate API to updating items in an order
 
 ### Acceptance Criteria 
 ```gherkin
 Given the service is running
 When I update an item in some order
 Then that item information should be changed and persisted in the database
```

**Comment by Matt-Kou** [comment]
Should we allow changing the order_id of an item? It seems to me that we shouldn't allow update_item to do so. If someone wants that it need to first delete and then add the item

**Comment by MahamArif** [comment]
Can you please clarify this question with the professor?
