### ISSUE TITLE
Create Database Model for Orders and Order Items

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#4]
**As an** Orders Manager/System Administrator
**I need** a database model and schema for orders
**So that** I can persist information in database as a result of CRUD operations on Orders resource.
   
 ### Details and Assumptions
We will be using PostGreSQL database. There will be two separate tables for orders and order items (one to many relationship). 

Order model will contain the following fields:
1. order id (primary key)
2. customer id
3. status (selection) (confirmed, in-progress, shipped, delivered, canceled)
4. created_on (date of order creation)
5. updated_on (date of order updation)

Order item model will contain the following fields:
1. item id (primary key)
2. product id
3. quantity
4. price
6. order id (foreign key)
7. created_on (date of item creation)
5. updated_on (date of item updation)

 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When a CRUD operation is performed on Order resource
 Then the information should be persisted in the database according to specified model
```

**Comment by MahamArif** [comment]
I believe we should use PostGreSQL, its already added in the repo.

**Comment by bf2285** [comment]
PostGreSQL - confirmed

**Comment by MahamArif** [comment]
For updating the order, we also need the status of the order, like order placed, order delivering, and the functionality to cancel an item or the entire order. So we can add a new field status to orders model.

**Comment by MahamArif** [comment]
The ability to cancel an item/order may go to a separate ticket.
