### ISSUE TITLE
Add workflow status badge

### ISSUE THREAD

**Issue by Matt-Kou** [CSCI-GA-2820-SP23-003/orders#48]
**As a** User who wants to use the code
**I need**  to see whether the CI build is passing
**So that** I would know whether the current commit is good to clone
   
 ### Details and Assumptions
 * The test units are run using `nosetests`. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 When initializing a pull request, pushing to github, or publishing a new release
 Then run GitHub Actions to test that the CI build is passing.
```

**Comment by MahamArif** [comment]
Duplicated by #59
