### ISSUE TITLE
Need to Add Query Ability to LIST Orders Route

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#50]
**As an** Order Manager
**I need**  the query capability in the LIST method for orders
**So that** I can retrieve orders with specific attributes
   
 ### Details and Assumptions
 * Allow querying orders using `customer_id` and `status` (order attributes)
 * Allow querying using item attributes (`product_id`). Return all orders that contain that `product_id` as one of its items.
 * Add methods to the database model to support querying.
 * Should be implemented as a filter on the LIST API method.
 * Should return the list of orders matching the specified query string.
   
 ### Acceptance Criteria  
   
 ```gherkin 
Given the service is running
When querying for orders with specific attributes
Then only the orders matching the selected fields/criteria will be returned.
```

**Comment by haoruigao** [comment]
filter by items_id doesn't make sense
