### ISSUE TITLE
Need to Add an Action Route - Cancel Order

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#51]
**As an** Order Manager 
**I need** the ability to cancel an order
**So that** I can proceed with order cancellation requests
   
 ### Details and Assumptions
 * The new route will be a `PUT` request to `/orders/<order_id>/cancel`.
 * `PUT` request will update the `status` attribute (already present in the model) to `CANCELLED`.
* If the order status is `SHIPPED`/`DELIVERED`/`CANCELLED`: 409 Conflict: request conflicted.
(We don't allow users to cancel orders after Shipped)
   
 ### Acceptance Criteria  
 ```gherkin
 Given the service is running
 When I request to cancel the order
 Then the order should have its status changed to CANCELLED
```

**Comment by bf2285** [comment]
What kind of action should we add?

**Comment by haoruigao** [comment]
Some updates on this:
If the order status is Shipped/Delivered/Cancelled: 409 Conflict: request conflicted.
(We don't allow users to cancel orders after Shipped)
