### ISSUE TITLE
Deploy the Orders Service to the Kubernetes Cluster

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#52]
**As a** User
**I need** the service to be publicly available on Kubernetes
**So that** I can use it from the Internet
   
 ### Details and Assumptions
 * Create the necessary Kubernetes metadata files for deployment `(deployment.yaml, service.yaml, secrets.yaml, postgres.yaml, etc.)` file so that Kubernetes will know how to
deploy the application.
 * Use the Kubernetes CLI `kubectl` command to deploy the service to the Kubernetes cluster.
 * Get the IP address of the worker node and combine it with the port to go to the URL of the service and make sure that it works.
 * Development port is: `31001` and the Production port is:`31002`
   
 ### Acceptance Criteria  
   
 ```gherkin
Given I have created the required files to deploy service on Kubernetes
When I issue a `kubectl apply -f deploy`
Then the service successfully deploys to Kubernetes
```

**Comment by MahamArif** [comment]
![Screenshot 2023-04-03 at 6.59.19 PM.png](https://images.zenhubusercontent.com/63e5d712708014177ac1a188/3858142a-1ac2-4290-b93b-801c905108ef)

**Comment by MahamArif** [comment]
![Screenshot 2023-04-03 at 7.02.39 PM.png](https://images.zenhubusercontent.com/63e5d712708014177ac1a188/dc3f9763-d5f8-4c30-8e1c-0dd282099057)
