### ISSUE TITLE
Add a single page UI to administer the application

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#53]
**As a** Developer
**I need** the initial UI setup in the application
**So that** I can add UI functionalities for CRUD operations.
   
 ### Details and Assumptions
 * Add a simple single-page UI file to the application.
 * Add the necessary configurations for UI to display.
 * This story will not include creating any CRUD functionality for the UI (only the basic setup).
 * Adding a `static` folder to the service, and copying all CSS and bootstrap files.
 * Add an empty `index.html` and corresponding `rest-api.js` file.
 * Replace the root URL in the `service/routes.py` to point to the HTML.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running and the initial UI setup is done
 When I add CRUD functionality for UI
 Then the UI should display those elements on the webpage.
```

**Comment by MahamArif** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/53?planning-poker) with Zenhub @bf2285 @haoruigao @MahamArif @Matt-Kou @SteambreadC
