### ISSUE TITLE
Add Swagger annotations to Order service

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#54]
**As a** Orders Manager/System Administrator
**I need** the ability to access API docs
**So that** I know what data to send to the Orders API
   
 ### Details and Assumptions
 * Add Swagger annotations to the Orders service to document the REST API using Flask-RESTX.
 * The documentation API must be available at: `/apidocs/`.
 * Add Swagger data models to document the API payloads.
 * Ensure that the Swagger docs work correctly and specify the data model so that others know what to send to the APIs.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the Order service is running and Swagger annotations are added
When I access the /apidocs/
Then I can access the API documentation of what data to send to each API.
```

**Comment by Matt-Kou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/54?planning-poker) with Zenhub @bf2285 @haoruigao @MahamArif @Matt-Kou
