### ISSUE TITLE
Setup a simple 2 stage DevOps Pipeline

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#55]
**As an** Orders Manager/System Administrator
**I need** the ability to automate build and deploy stages in a pipeline
**So that** build is deployed automatically on every push to the master branch
   
 ### Details and Assumptions
 * Set up the DevOps Continuous Delivery Pipeline in IBM Cloud to build and deploy the project when the master branch changes.
 * Connect this DevOps pipeline to the GitHub repository for the project via a webhook.
 * The full Pipeline must have 4 stages: Build, Deploy, Test, and Production. This story will implement the first two stages (build and deploy). The next two stages will be implemented in #73.
 * Add a Build stage that has a Job to checkout the code from GitHub, a Job to run the units tests with `nosetests` and a job to Build a Docker Image and push it to the IBM Cloud Container Registry. (3 jobs in total).
 * Add a `Dev` Deploy Stage to the pipeline to deploy your microservice to the `dev namespace` in your Kubernetes cluster using the Docker image from the previous stage, if the previous stage completes successfully.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the service is running and the pipeline is setup
Whenever I merge a Pull Request 
Then the build is automatically deployed to the dev namespace
```

**Comment by MahamArif** [comment]
![Screenshot 2023-04-08 at 10.17.43 PM.png](https://images.zenhubusercontent.com/63e5d712708014177ac1a188/da9490ed-1fad-461a-b1fe-5509fb1791fb)
