### ISSUE TITLE
Need to Add a Query Route for Item

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#56]
**As a** Order Manager
**I need** a query capability to the list method for items for a given order
**So that** extract items with certain traits
   
 ### Details and Assumptions
 * See details about database model design in README
 * Allows query for multiple things (quantity, price, etc)
 * Return **list of items**
 * This is a filter on the List method, NOT a new method
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is running
 When querying for a category
 Then only the items with selected category/categories will be listed
```

**Comment by bf2285** [comment]
Need more thoughts on this. This is just an idea, not sure if we need this

**Comment by MahamArif** [comment]
As discussed with the professor, we can query the attributes of the item inside the LIST Orders API. For instance, we can query all orders containing a particular product id. Also,  LIST API for items only returns items for a single order, therefore there are not many items to further apply a query filter. Thus, this ticket is not needed.
