### ISSUE TITLE
Configure GitHub Actions (CI Pipeline) to run BDD tests on every Pull Request and push to master

### ISSUE THREAD

**Issue by haoruigao** [CSCI-GA-2820-SP23-003/orders#58]
**As a** Developer
**I need**  the ability to see whether the pull requests and pushes to the master branch are stable (passing all the BDD tests)
**So that** I would know whether the current pull request is good to merge and that the new changes are not breaking older functionality
   
 ### Details and Assumptions
 * Create a .github/workflows/bdd.yml file.
 * Configure GitHub Actions to run the BDD test cases every time someone pushes to
the master branch or submits a Pull Request.
 * Should NOT accept a Pull Request with tests that are failing. 
 * The tests are run using `behave`. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a developer makes some code changes
When a PR is raised for those changes or it is pushed to the master branch
Then Github Actions should check if all the integration tests are passing or not.
```

**Comment by MahamArif** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/58?planning-poker) with Zenhub @bf2285 @haoruigao @MahamArif @Matt-Kou @SteambreadC
