### ISSUE TITLE
Need the ability to Read an Order

### ISSUE THREAD

**Issue by haoruigao** [CSCI-GA-2820-SP23-003/orders#6]
As an **Order Manager/System Administrator**
I need the ability to **read** an order
So that I can check the order details when required.

### Details and Assumptions
The API will return the following order information:

1. Order id
2. Customer id
3. List of items in the order (each with product id, quantity, and price)

- Add location URL in create order API #3.

### Acceptance Criteria
```gherkin
Given the service is running
When I read an order through an order id
Then the database will return the order data
```

**Comment by bf2285** [comment]
Should we return the order id?

**Comment by MahamArif** [comment]
Please add location_url to create API as part of this ticket. The location URL for getting an order in the create API was blocked because of this ticket.
