### ISSUE TITLE
Refactor Orders Service to use Flask-RESTX

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#72]
**As a** Developer
**I need** the ability to refactor code to use Flask-RESTX
**So that** I can provide Swagger documentation with little effort
   
 ### Details and Assumptions
 * Refactor the micro-service to use Flask-RESTX following the file layout outlined in `lab-flask-restplus-swagger`.
 * Initialize the application object `api`.
 * Refactor the code to include three classes `OrderResource`, `OrderCollection`, `CancelOrder` for the order routes.
 * Add similar three classes for item routes.
 * Separate order and item classes into two files `order_routes.py` and `item_routes.py`.
 * Copy and paste routes implementation from already implemented routes.
 * Run unit tests to ensure everything works fine. No tests should be changed ideally.
 * All HTTP errors return JSON error messages and not HTML.
 * Delete most of the `error_handlers.py` file because Flask-RESTX will these errors.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the service is running 
and the Order service is refactored to use Flask-RESTX
When we add Swagger documentation
Then the API docs should be available to users without many changes.
```

**Comment by MahamArif** [comment]
This tutorial is helpful to get started with Flask-RESTX https://flask-restx.readthedocs.io/en/latest/quickstart.html

**Comment by Matt-Kou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/72?planning-poker) with Zenhub @Matt-Kou @bf2285 @haoruigao @MahamArif

**Comment by MahamArif** [comment]
Updated Flask-RESTX==1.1.0 in this ticket.
