### ISSUE TITLE
Invite Team to IBM Cloud Account

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#80]
**As a** Github Repository Maintainer
**I need** to invite all team members on IBM Cloud
**So that** the team can deploy to Kubernetes cluster

### Details and Assumptions
* Every member of the team will create their own IBM Accounts.
* Please comment below if you are done setting up your IBM Cloud.

### Acceptance Criteria
```gherkin
Given all IBM accounts being created and invited to share a K8 cluster
When any group member try to deploy to K8 cluster
Then the deployment should be succeeded.
```

**Comment by haoruigao** [comment]
All set for me, account: hg2524@nyu.edu

**Comment by Matt-Kou** [comment]
yifeng.kou@nyu.edu

**Comment by SteambreadC** [comment]
Solved my issue. Please invite me using: ziteng.cao@nyu.edu

**Comment by MahamArif** [comment]
I have invited all the emails to my IBM cloud account and verified with @haoruigao that the project cluster `nyu-devops-orders` is showing up in Kubernetes. So I am marking this story as done.
