### ISSUE TITLE
Add UI functionality for Read Item

### ISSUE THREAD

**Issue by bf2285** [CSCI-GA-2820-SP23-003/orders#89]
**As an** Orders Manager/System Administrator
**I need** the ability to read an item through UI
**So that**  I don't need to use Postman for sending API Requests and check the order details when required.
   
 ### Details and Assumptions
 * Add elements for displaying item in the UI file.
 * BDD scenarios for Read Item will also be a part of this story.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When I read an item by id
 Then the UI should display the item data
```

**Comment by Matt-Kou** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-003-63e5277201a8350017039888/issues/CSCI-GA-2820-SP23-003/orders/89?planning-poker) with Zenhub @bf2285 @haoruigao @MahamArif @Matt-Kou
