### ISSUE TITLE
Add UI functionality for List Items

### ISSUE THREAD

**Issue by MahamArif** [CSCI-GA-2820-SP23-003/orders#90]
**As a** Orders Manager/System Administrator
**I need** the ability to create order items through UI
**So that** I don't need to use Postman for sending API Requests.
   
 ### Details and Assumptions
 * Add elements for creating orders in the UI file.
 * BDD scenarios for Create Order will also be a part of this story.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the service is running
When an order item is created through the UI
Then it should be persisted in the database
```

**Comment by bf2285** [comment]
Duplicate
